version: '3.8'

services:
    database:
        image: postgres
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        volumes:
            - postgres:/data/postgres
        ports:
            - '5432:5432'

volumes:
    postgres:
