version: '3.8'

services:
    prod_api:
        environment:
            - NODE_ENV='production'
            - DOMAIN_URL=${DOMAIN_URL}
            - DATABASE_URL=${DATABASE_URL}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - CACHE_URL=${CACHE_URL}
            - CACHE_PASSWORD=${CACHE_PASSWORD}
            - PORT=${PORT}
            - RATE_LIMIT_FIXED_WINDOW_IN_MINUTES=${RATE_LIMIT_FIXED_WINDOW_IN_MINUTES}
            - RATE_LIMIT_TOKEN=${RATE_LIMIT_TOKEN}
        image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_IMAGE}:latest
        expose:
            - ${PORT}

    nginx:
        image: nginx:latest
        volumes:
            - ../nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '80:80'
        depends_on:
            - prod_api
