version: '3.8'

services:
    database_pg:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres:/data/postgres
        ports:
            - '5432:5432'
    database_mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ShortenedUrls
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - '3306:3306'
    cache_redis:
        image: redis:7.0.5
        restart: always
        command: redis-server --requirepass ${CACHE_PASSWORD}
        volumes:
            - cache:/data/redis
        ports:
            - '6379:6379'
    adminer:
        image: adminer
        restart: always
        ports:
            - '8080:8080'

volumes:
    postgres:
    mysql:
    cache:
